[package]
name = "cli"
version = "0.0.0"
edition = "2021"
description = "Database engine CLI client."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engine-core = { path = "../engine-core" }
